# Simple Makefile for devkitPro / devkitARM
# Requires devkitPro (https://devkitpro.org/wiki/Getting_Started)
# Usage:
# 1) Install devkitPro and devkitARM
# 2) Run `make` in this directory to produce magic_valley.gba

TARGET := magic_valley
BUILD := build
SOURCES := source/main.c

# Include the devkitARM rules (the system must have DEVKITARM installed)
include $(DEVKITARM)/gba_rules
